name: Fetch latest data for Cardiff Central

on:
  repository_dispatch:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        mkdir -p data/cardiff_central && cd data/cardiff_central
        NOW=$(date +%s)
        curl 'https://nreservices.nationalrail.co.uk/live-info' -o cardiff_central_${NOW}_arrival.json -H 'content-type: application/json' -H 'origin: https://www.nationalrail.co.uk' -H 'referer: https://www.nationalrail.co.uk/' --data-raw $'{"query":"query ArrivalBoard($crs: String\u0021, $fromCrs: String, $time: String, $serviceTypes: [NreServiceMode], $timeWindow: Int, $numRows: Int) {\\n  ArrivalBoard(\\n    crs: $crs\\n    fromCrs: $fromCrs\\n    time: $time\\n    serviceTypes: $serviceTypes\\n    timeWindow: $timeWindow\\n    numRows: $numRows\\n  ) {\\n    ...boardResult\\n  }\\n}\\n\\nfragment boardResult on NreStationBoard {\\n  generatedAt\\n  nrccMessages {\\n    message\\n    severity\\n  }\\n  departureStation {\\n    locationName\\n    crs\\n    via\\n  }\\n  filterStation {\\n    locationName\\n    crs\\n    via\\n  }\\n  services {\\n    rid\\n    trainUid\\n    serviceType {\\n      mode\\n      category\\n    }\\n    origin {\\n      locationName\\n      crs\\n      via\\n    }\\n    destination {\\n      locationName\\n      crs\\n      via\\n    }\\n    journeyDetails {\\n      from {\\n        locationName\\n        crs\\n        via\\n      }\\n      to {\\n        locationName\\n        crs\\n        via\\n      }\\n      stops\\n      departureInfo {\\n        scheduled\\n        estimated\\n        actual\\n      }\\n      arrivalInfo {\\n        scheduled\\n        estimated\\n        actual\\n      }\\n    }\\n    operator {\\n      name\\n      code\\n    }\\n    status {\\n      status\\n      delayReason\\n      cancelReason\\n    }\\n    departureInfo {\\n      scheduled\\n      estimated\\n      actual\\n    }\\n    arrivalInfo {\\n      scheduled\\n      estimated\\n      actual\\n    }\\n    platform\\n    loadingLevel\\n  }\\n}\\n","variables":{"crs":"CDF","timeWindow":120,"serviceTypes":["Bus","Ferry","Train"]},"operationName":"ArrivalBoard"}'
    - name: Commit and push data if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data for Cardiff Central: ${timestamp}" || exit 0
        git push
